#!/usr/bin/env python3
import sys
from struct import pack


def main(args):
    if len(args) < 2:
        exit("Usage: mkload <in_image> <out_data>")

    with open(args[0], "rb") as file:
        in_data = file.read()

    with open(args[1], "wb") as file:
        file.write(pack("<I", len(in_data)))
        file.write(in_data)


if __name__ == "__main__":
    main(sys.argv[1:])
